name: Hexo Deployment

on:
  push:
    branches: [main]

jobs:
  hexo-deployment:
    runs-on: ubuntu-20.04
    env:
      TZ: Asia/Shanghai

    steps:
    - name: Checkout source
      uses: actions/checkout@v4.2.2
      with:
        submodules: true

    - name: Setup Node.js
      uses: actions/setup-node@v4.1.0
      with:
        node-version: '22.11.0'

    - name: Install dependencies & Generate static files
      run: |
        npm install --location=global hexo-cli
        npm i
        hexo clean
        hexo g
        
    - name: Deploy to server
      uses: easingthemes/ssh-deploy@v5.1.0
      env:
        SSH_PRIVATE_KEY: '${{ secrets.SSH_PRIVATE_KEY }}'
        REMOTE_HOST: '${{ secrets.SERVER_IP }}'
        REMOTE_USER: '${{ secrets.USER }}'
        REMOTE_PORT: '${{ secrets.PORT }}'
        TARGET: '/opt/1panel/apps/openresty/openresty/www/sites/blog.akyuu.cn/index'
        ARGS: "-avz --delete --chown=www:www"
        SOURCE: "public/" 
        SCRIPT_BEFORE: ls
